version: '3.8'
services:
  db:
    container_name: noice_parking_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes: 
      - ./setup/createDB.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./setup/sampleRecords.sql:/docker-entrypoint-initdb.d/samples.sql
  api:
    depends_on:
      - db
    build: .
    restart: always
    env_file: ./.env
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
    stdin_open: true
    tty: true