version: '3.8'
services:
  db:
    container_name: noice_parking_db
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
    ports:
      - '5432:5432'
    volumes: 
      - ./createDB.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./sampleRecords.sql:/docker-entrypoint-initdb.d/samples.sql